### ISSUE TITLE
crash on launch[fabric 1.15.2]

### ISSUE THREAD

**Issue by SDUBZ** [JSJBDEV/GiveMeHats#1]
crash log:
https://gist.githubusercontent.com/SDUBZ/7d5e401b17b0b3fe420cb853032846e7/raw/d944426734e4011811c1cce34c90608ca806381e/crash-2020-06-03_18.44.18-client.txt

**Comment by JSJBDEV** [comment]
Hey there, just looked at that and the error seems to suggest that method isnt there so potentially another mode changes it, what I can do is push an update without entities being able to spawn with them (its very rare anyway) and at some point I will change the method it looks at to make it work.

tl;dr I will make an update where you can only find hats in dungeon chests until further notice

**Comment by JSJBDEV** [comment]
when curse approves it, GiveMeHats has been push with a new update that fixes that error (most probably) and also adds a new hat, thank you for you time and support, feel free to open another issue if something arises again :)
