### ISSUE TITLE
Items drop separately after death

### ISSUE THREAD

**Issue by kotx** [JSJBDEV/GiveMeHats#14]
[Charm](https://github.com/svenhjol/Charm) adds a new "Totem of Preserving" that places all items into a totem after death. All modded items except for hats are placed in the totem correctly. Hats drop separately. Not sure if this is a bug on this mod's end, but that seems like the likelier option.

**Comment by JSJBDEV** [comment]
this was probably a trinkets issue if anything, i dont do anything special with the items beyond the base trinket class
