### ISSUE TITLE
Sailor Hat is Broken | Balance Change

### ISSUE THREAD

**Issue by KavisKryptic** [JSJBDEV/GiveMeHats#15]
I would just like to request a balance change/fix to the sailor hat since I'm not sure if it's intentional.

The sailor hat quite literally enables you to be able to fly. You can place the boat a couple dozen blocks up and virtually fly. 

And players who have this load a ridiculous amount of chunks. It nulls the need for an elytra, or anything else for mobility.

**Comment by JSJBDEV** [comment]
will be fixed in next update today, now it only works in water, thanks!
