### ISSUE TITLE
Dwarven Helm Cannot Be Equipped

### ISSUE THREAD

**Issue by JasonTheCPE** [JSJBDEV/GiveMeHats#19]
Found a Dwarven Helm while playing Another Quality Modpack 2 but was unable to equip it. Seems like its missing the whatever tag that allows it to be equipped to the Hat slot.

**Comment by JasonTheCPE** [comment]
I looked into the code, looks like its missing from the default config?

**Comment by JSJBDEV** [comment]
in the code Dwarven hat is defintely registered in that hat slot, using the tag, otherwise I wouldnt have been able to take a screenshot of it for the gif on the cf page, perhaps something isnt quite right with the modpack? do other hats do this?

**Comment by JSJBDEV** [comment]
(see https://github.com/JSJBDEV/GiveMeHats/blob/51542a32a42f0abe505bee86dd9e081aae9bd10b/src/main/resources/data/trinkets/tags/items/head/hat.json#L30)

**Comment by JasonTheCPE** [comment]
I added that line to the config for my world and it still won't let me put it into the head slot for some reason, possibly something else to do with the pack though. I assume its working standalone so I'll close this issue.
