### ISSUE TITLE
Tippity top hat renders inverted

### ISSUE THREAD

**Issue by ejektaflex** [JSJBDEV/GiveMeHats#2]
![image](https://user-images.githubusercontent.com/23628421/85637941-2e5e7980-b64a-11ea-8453-138f060ede3f.png)

This happens with Minecraft 1.16 with Give Me Hats! version 1.2.0. This happens with the regular top hat and the fez, as well. I assume it might happen with all of the hats?

Also, they can stack up to 64. You can wear 64 tippity top hats :^)

**Comment by JSJBDEV** [comment]
As seen on the other issue, however this one might be not as simple to fix, since i don't directly control rendering, but I may have seen this issue before, so I'll look into it when I can

**Comment by JSJBDEV** [comment]
Also fixed in 1.2.5 thanks again!
