### ISSUE TITLE
[Windows Defender] Falsely Identifying a trojan in GiveMeHats

### ISSUE THREAD

**Issue by itsdinkd** [JSJBDEV/GiveMeHats#21]
https://github.com/ShetiPhian/Localizations-and-Issues/issues/349

As mentioned to ShetiPhian, people who are downloading my modpack "Another Quality Modpack 2" are getting false negatives of viruses due to Windows Defender sucking ass. They download from CF, and if they have windows defender, 9/10 several mods are getting quarantined. This is preventing them from playing the pack (Not blaming you)

I wanted to give you a heads up, as ShetiPhian also suggested. I will be reporting to the other mods that were falsely identified as a virus. I had roughly over 10 people that complained about this today in our discord and they all downloaded the pack from CF. 

![image](https://user-images.githubusercontent.com/35115304/166414505-bc95e9c5-2e4f-4542-8787-bd800a765b4d.png)

**Comment by JSJBDEV** [comment]
Hello
Oh dear that does feel like quite the problem, the hope is of course they have been falsely reported and there isnt some problem CF side.

For transparency I will upload the latest source code for the forge and fabric version here today, and I'll aim to make a new release here as well so you can do some checking, hopefully however these are just false positives

**Comment by ShetiPhian** [comment]
I've gotten the all clear from Microsoft Security Intelligence 
Figuring out how was a bit annoying and was rejected at first, so here is what worked.
[It will take a while to clear your file, as we are low priority]

Verify the false positive with Kaspersky (https://opentip.kaspersky.com)

Next go to: https://www.microsoft.com/en-us/wdsi/filesubmission
Choose Software developer and continue
Security product is Microsoft Defender Antivirus
Type anything you want into Company Name
"No" to Microsoft support case number
Skip Software Assurance ID, its for enterprise clients
"No — remove the file automatically after a period of inactivity"
What do you believe this file is? = Incorrectly detected as malware/malicious
Detection name = Trojan:Script/Wacatac.B!ml

**Comment by JSJBDEV** [comment]
hopefully curseforge (which is where I assume the false positive derives) can also fix there system for this, if its affecting multiple mods then clearly its not mod specific, I am interested to see if a non curseforge upload (such as the tag on this repo) has this problem? I havent specifically had it triggered on me but I doubt im doing it the correct way to see this output.

assuming there is no overarching fix on CFs end, Ill go through that process in a few days, thanks for the info

**Comment by JSJBDEV** [comment]
@itsdinkd would you be able to try and see if GiveMeHats works from the github release? if it does not then we can definitely blame defender and ill get on to doing the false positive detection, just want to confirm if its a CF thing or if its a Defender thing

edit: there was another line here but it is irrelevant

**Comment by JSJBDEV** [comment]
Im not entirely sure if this has been fixed another side now, it seems to all work with me, the issue can be reopened if necessary, ill assume until then that I dont have to go through the false positive process, but I have it set up just in case (since I cant get it to false positive)

**Comment by itsdinkd** [comment]
Hey sorry, this slipped past me. all seems well for now
