### ISSUE TITLE
Forge Server Crashing on startup (1.18.2)

### ISSUE THREAD

**Issue by Dameworth** [JSJBDEV/GiveMeHats#22]
Having an issue getting Give Me Hats to work on a Forge Server in 1.18.2 
[crash-2022-05-03_19.44.02-fml.txt](https://github.com/JSJBDEV/GiveMeHats/files/8616927/crash-2022-05-03_19.44.02-fml.txt)

Exception: java.lang.ClassNotFoundException: com.mojang.blaze3d.vertex.PoseStack

**Comment by JSJBDEV** [comment]
Ah yes I forgot forge really doesn't like compiling side only methods and such, I can't do this right now but will probably be able to do so in about 30 hours

**Comment by JSJBDEV** [comment]
fixed in version 2.0.1 https://www.curseforge.com/minecraft/mc-mods/give-me-hats/files/3781213 please reopen an issue if the issue persists :D
