### ISSUE TITLE
[1.18.2-2.0.1] Give Me Hat's mixin into container loot crashes when containers are not broken by players

### ISSUE THREAD

**Issue by TelepathicGrunt** [JSJBDEV/GiveMeHats#23]
I got this report on my mod page about chests/dispensers in my structure are crashing when broken by TNT.
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures#c1117

This is the user's crashlog:
[crashlog.txt](https://github.com/JSJBDEV/GiveMeHats/files/8682833/crashlog.txt)

I see the crash is caused by a nullpointerexception in a mixin called `handler$zno000$loot` for the RandomizableContainerBlockEntity class. To the right of it, I see `pl:mixin:APP:gmh.mixins.json:LootMixin` signaling that a mod with gmh.mixins.json file is involved. So going through the modlist, I see Give Me Hats fits those initials. 

Which then led me to here and found that mixin called loot with it's unsafe call to the player which can be null through normal minecraft gameplay:
https://github.com/JSJBDEV/GiveMeHats/blob/9220062207281f0e1101702be1834cd57fc9ad71/src/main/java/gd/rf/acro/givemehats/mixin/LootMixin.java#L48

I think a simple solution here is to replace `Random random = player.getRandom();` with `Random random = world.getRandom();` since you already check if the world is null or not. That would prevent the crash with any container block being broken by non-player actions. Also, it may be a good idea to prefix your mixin names with your modid. Like instead of this mixin being called "loot", call it "givemehats_loot" which will show up in the tracktrace and make it much easier for users to know what mod's mixin is having trouble.

I hope this helps!

**Comment by JSJBDEV** [comment]
Sounds great, will do, thank you for providing a solution as well 😁 will push a fix tomorrow (in about 19 hours or so)

**Comment by Sebas-Re** [comment]
I'm also having this issue, but with vanilla structures and dispensers too (Ex. when a dispenser activates in a jungle temple, the server crashes)

https://paste.corebot.dev/tiyuvopefa.php

**Comment by JSJBDEV** [comment]
Yeah I imagine it'll happen with all of them, in sorry I have not had time recently to fix this, but I will as soon as I can

**Comment by Sebas-Re** [comment]
That's ok, thanks a lot <3

**Comment by JSJBDEV** [comment]
just uploaded new version for forge and fabric using the fix, please tell me if you find any other problems with it, and then I will close the Issue

**Comment by itsdinkd** [comment]
Btw, this also happened because the config was not automatically updated to remove deerstalker once it was removed from the mod. 

so it having deerstalker=1 basically caused this. i would recommend updating the config to add new hats / remove hats on updates

**Comment by JSJBDEV** [comment]
I don't think the config can cause that? As in the other issue it defaults to existing, for specifically the deer stalker it was changed not removed, config should have been regenerated as of 2.0 because of that it's technically not compatible due to some modifications for hat names and the luck system, I'm not sure when you first got the mod, but that is probably the reason if it was before 2.0 :)

**Comment by itsdinkd** [comment]
This crash is still occuring because some loot tables are **still** trying to generate this hat

https://pastebin.com/UnSnP4tL

**Comment by JSJBDEV** [comment]
> This crash is still occuring because some loot tables are **still** trying to generate this hat
> 
> https://pastebin.com/UnSnP4tL

I believe this to be a different error to do with trying to load my data into dispensers then they have space for, we can keep it here as it is similar but it is not the same

**Comment by itsdinkd** [comment]
> > This crash is still occuring because some loot tables are **still** trying to generate this hat
> > https://pastebin.com/UnSnP4tL
> 
> I believe this to be a different error to do with trying to load my data into dispensers then they have space for, we can keep it here as it is similar but it is not the same

The main issue is its trying to generate a hat that is disabled (or at least this is what I'm told by people who are experiencing this crash. this is what happened back when I reported this a month ago and you fixed a couple things) and is crashing

**Comment by JSJBDEV** [comment]
that is a problem, but this is actually a different error, it was trying to et an inventory stack from slot 0 -27 in all inventories, I did not realise dispensers and such where counted, but i think ive fixed it now, might actually check for >9 slots so it doesnt appear in them

**Comment by JSJBDEV** [comment]
see other issue, but 2.0.4 should fix this once and for all
