### ISSUE TITLE
[1.18.2 Fabric] Config not showing new hats

### ISSUE THREAD

**Issue by itsdinkd** [JSJBDEV/GiveMeHats#24]
Hello. The last 5 hats are not being generated in the config. does this matter? should I manually put them in? halo, dwarven, viking, etc, etc.

**Comment by JSJBDEV** [comment]
Manually putting them in will work, if the config is not present it defaults to the hat exists on all config items, I should make it default gen however

**Comment by itsdinkd** [comment]
I highly suggest redoing the config system. please take no offense but it is a disaster. It doesn't auto update, when you remove a hat, it causes major issues as you then have to remove the line from the config (something the mod itself needs to do). If you disable a hat from generating, it breaks all the hats from being equippable, forcing you to create a trinket datapack. its a mess. I am on the cusp of removing GiveMeHats from Another Quality Modpack strictly because of this.

currently, the hat you removed in 1.18.2, the deer stalker hat is still giving issues. even removing it from the config it still generates in the world and just shows the icon in the loot. it actually crashed someone when they clicked on it, but when they joined their game again, it turned into a visual icon only, not interactable in that loot table..

**Comment by JSJBDEV** [comment]
That is very strange.
What do you mean by "remove the hat"? If you want to disable the hat you use the config (or did I misinterpret something there?)
That deerstalker hat hasn't been removed, it's been renamed, the config is slightly different but shouldn't cause so many problems.
I will have a look at this today.

**Comment by JSJBDEV** [comment]
Oh I think I know why this happens and it is truly a fabric only problem, in fabric the hats actually don't get registered if they are disabled which breaks the trinket system which kinda sucks, will allign it with the forge version which registers them but doesn't put them in loot containers

**Comment by JSJBDEV** [comment]
2.0.4 should fix all your issues, it has been uploaded

**Comment by JSJBDEV** [comment]
for reference, hats will not be removed from the game if you disable them, they just wont spawn, I can potentially make a change to remove them as well, but as it stands i disabled like 15 hats and it did not break as of the new version

**Comment by JSJBDEV** [comment]
also, all the hats are in the default config now
