### ISSUE TITLE
1.18.2 Equiping any hat will flip other curios slots

### ISSUE THREAD

**Issue by Nawaque** [JSJBDEV/GiveMeHats#25]
When i equip any hat, all the items in the other curios slots flip.
Im using forge, 1.18.2 and the others mods are artifacts, sophisticated backpack and tool belt.
![image](https://user-images.githubusercontent.com/84165277/170289469-89ec5523-e942-4e68-abaf-8f2d3273ca29.png)
![image](https://user-images.githubusercontent.com/84165277/170289561-a3eac9a3-814d-4034-b388-872c799e2c96.png)
![image](https://user-images.githubusercontent.com/84165277/170289676-cdf0899d-0570-4c2f-a2e6-005d8b2bdcb2.png)

**Comment by JSJBDEV** [comment]
Lol that's a pretty funny bug. I'm gonna assume it's something to do with the way I render things (all the hats need to be flipped to render properly, but I kinda assumed the engine would flip it back for everything else)

Will have a look when I get time, I think it should be easy enough to fix

**Comment by JSJBDEV** [comment]
when 2.0.3 turns up on CF (it has been submitted) please have a test, I tested with artifacts and it seemed to work fine

**Comment by Nawaque** [comment]
It works perfectly! Thank you, this was the fastest fix I'v ever seen on github.
![image](https://user-images.githubusercontent.com/84165277/170396942-cc3b7223-9906-43f9-af51-1b7de25b3b48.png)
