### ISSUE TITLE
Fabric 1.19 - 2.5.0 Crashes

### ISSUE THREAD

**Issue by Haihatu** [JSJBDEV/GiveMeHats#26]
I don't know much about coding or anything but some spongepowered injection error is not letting MC even boot.
[crashlog.txt](https://github.com/JSJBDEV/GiveMeHats/files/9152574/crashlog.txt)

**Comment by JSJBDEV** [comment]
Are you sure your in the right place? you don't appear to actually have GiveMeHats installed
