### ISSUE TITLE
Slow fall does not negate fall damage

### ISSUE THREAD

**Issue by ejektaflex** [JSJBDEV/GiveMeHats#3]
This happens with Minecraft 1.16 with Give Me Hats! version 1.2.0.

You still take damage when jumping off of a cliff, but you still fall very slowly. 

A side note: It's a little too slow for my liking. Something about halfway between normal fall speed and the current speed would probably be a lot better.

Thank you, and excellent work!

**Comment by JSJBDEV** [comment]
I didn't actually get around to testing all the hats in 1.16 so thank you for the response, I will look into this (and the render issue) probably on the coming days after ModFest 1.16 finishes then I'll fix this and port the rest of my mods, thanks 😄

**Comment by JSJBDEV** [comment]
Fixed in update 1.2.5, thank you!
