### ISSUE TITLE
Update source for 3.0.1

### ISSUE THREAD

**Issue by korewaChino** [JSJBDEV/GiveMeHats#30]
Can we finally get an update on this repo? There's a new release yet seems like the changes aren't even pushed here

**Comment by JSJBDEV** [comment]
oh yeah I should probably do that sometime, I can assure you very little has changed in terms of content, I haven't had enough patience to actually add hats recently

**Comment by korewaChino** [comment]
Could you also please make this repository upstream for all changes for the mod? Would not make sense to have source code link posted on Modrinth if it was never updated.

This will also ensure that other contributors can send patches to this mod

**Comment by JSJBDEV** [comment]
At some point the source for this did break so once I work out how to connect it back up again ill upload the code

**Comment by JSJBDEV** [comment]
the code is uploaded now, since it currently only targets 1.20.1 as supported thats the main branch but I can always add branches later for older versions, hopefully I have my intellij set up now so that it actually knows this is the remote
