### ISSUE TITLE
Crashed in the latest version

### ISSUE THREAD

**Issue by linzexin022** [JSJBDEV/GiveMeHats#4]
[crash-2020-07-12_21.13.13-client.txt](https://github.com/JSJBDEV/GiveMeHats/files/4908547/crash-2020-07-12_21.13.13-client.txt)
It is a nice mod but crashed when I was testing mods. I also used these mods: Dark Loading Screen; Fabric API; Fabric Language Kotlin; Inventory Profiles; Mod Menu; Roughly Enough Items & Resources. I've uploaded the crash report. Please check it and have a good day!

**Comment by JSJBDEV** [comment]
GiveMeHats Require the mod trinkets
https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric im not sure how you installed your mods, but Id assume it didnt install automatically :D

**Comment by linzexin022** [comment]
Ah look how careless I am! Thank you hahah!
