### ISSUE TITLE
version in fabric.mod.json not consistent with version

### ISSUE THREAD

**Issue by Linguardium** [JSJBDEV/GiveMeHats#5]
latest still shows 1.0.1
![image](https://user-images.githubusercontent.com/61733861/89078874-101b2600-d33a-11ea-97f7-7fadfe3573d1.png)

**Comment by JSJBDEV** [comment]
it was then I forgot which version it was on. basically the 1.16 build broke it
will fix this with next version

**Comment by JSJBDEV** [comment]
fixed for version 1.2.8
