### ISSUE TITLE
Issue with winged mod

### ISSUE THREAD

**Issue by Monster-Zer0** [JSJBDEV/GiveMeHats#6]
Fabric API 0.19.0+build.398-1.16
MC 1.16.2

give me hats v 1.2.8
winged v 1.4.0

when using Give me hats and wearing wings.

you get this

https://i.imgur.com/dyPFgxs.png

reporting this here and on their issues board just in case.

**Comment by JSJBDEV** [comment]
huh, thats a new one on me xD Im not sure I can specifically do anything about that if that is a problem, you may have to report it to the Trinkets author, Ill have a check but I dont have any code that should interfere, unless my trinkets or your trinkets is outdated

**Comment by JSJBDEV** [comment]
not sure if this ever got fixed, please reopen the issue if its a problem 1 year later here xD
